# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=255, null=True)),
                ('member2', models.CharField(blank=True, max_length=255, null=True)),
                ('member3', models.CharField(blank=True, max_length=255, null=True)),
                ('member4', models.CharField(blank=True, max_length=255, null=True)),
                ('member5', models.CharField(blank=True, max_length=255, null=True)),
                ('member6', models.CharField(blank=True, max_length=255, null=True)),
                ('subject1', models.CharField(choices=[('commers', 'Commers'), ('physics', 'Physics'), ('computers', 'Computers'), ('chemistry', 'Chemistry'), ('art', 'Art'), ('bio', 'Biology'), ('maths', 'Mathematics')], default='computers', max_length=10)),
                ('subject2', models.CharField(choices=[('commers', 'Commers'), ('physics', 'Physics'), ('computers', 'Computers'), ('chemistry', 'Chemistry'), ('art', 'Art'), ('bio', 'Biology'), ('maths', 'Mathematics')], default='computers', max_length=10)),
                ('subject3', models.CharField(choices=[('commers', 'Commers'), ('physics', 'Physics'), ('computers', 'Computers'), ('chemistry', 'Chemistry'), ('art', 'Art'), ('bio', 'Biology'), ('maths', 'Mathematics')], default='computers', max_length=10)),
                ('winner', models.BooleanField(default=False)),
                ('team_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
