# Generated by Django 4.2.6 on 2023-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member1_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
        migrations.AddField(
            model_name='team',
            name='member2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
        migrations.AddField(
            model_name='team',
            name='member3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
        migrations.AddField(
            model_name='team',
            name='member4_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
        migrations.AddField(
            model_name='team',
            name='member5_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
        migrations.AddField(
            model_name='team',
            name='member6_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
    ]
