# Generated by Django 4.2.6 on 2023-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_team_member1_picture_team_member2_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
