# Generated by Django 4.2.6 on 2023-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_member1_name', models.CharField(max_length=100)),
                ('org_member1_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member1_role', models.CharField(max_length=100)),
                ('org_member2_name', models.CharField(max_length=100)),
                ('org_member2_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member2_role', models.CharField(max_length=100)),
                ('org_member3_name', models.CharField(max_length=100)),
                ('org_member3_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member3_role', models.CharField(max_length=100)),
                ('org_member4_name', models.CharField(max_length=100)),
                ('org_member4_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member4_role', models.CharField(max_length=100)),
                ('org_member5_name', models.CharField(max_length=100)),
                ('org_member5_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member5_role', models.CharField(max_length=100)),
                ('org_member6_name', models.CharField(max_length=100)),
                ('org_member6_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member6_role', models.CharField(max_length=100)),
                ('org_member7_name', models.CharField(max_length=100)),
                ('org_member7_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member7_role', models.CharField(max_length=100)),
                ('org_member8_name', models.CharField(max_length=100)),
                ('org_member8_profile_pic', models.ImageField(upload_to='team_pics/')),
                ('org_member8_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Updates',
            new_name='News',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='update',
            new_name='news',
        ),
    ]
